// src/components/HealthCardView.tsx
// Renders a HealthCard with QR code, seller declaration, and AI assessment.
// Ported from ReRoute — adapted to Tailwind v4.

import type { HealthCard } from "../lib/types";

interface Props {
  card: HealthCard;
  qrBase64?: string | null;
}

const CONDITION_TEXT: Record<string, string> = {
  "Like New": "text-emerald-600",
  Good: "text-blue-600",
  Fair: "text-orange-600",
  Poor: "text-red-700",
};

export default function HealthCardView({ card, qrBase64 }: Props) {
  const condText = CONDITION_TEXT[card.condition_grade] ?? "text-gray-500";

  return (
    <div className="border-2 border-amzn-orange rounded p-4 bg-white text-[13px] max-w-[500px]">
      {/* Header */}
      <div className="flex justify-between items-start gap-4 mb-2.5">
        <div>
          <div className="text-[15px] font-bold text-gray-900">Amazon Product Health Card</div>
          <div className="text-[11px] text-gray-400 mt-0.5">{card.card_uuid}</div>
        </div>
        {qrBase64 ? (
          <img src={`data:image/png;base64,${qrBase64}`} alt="QR code" className="w-[70px] h-[70px]" />
        ) : (
          <div className="w-[70px] h-[70px] border border-gray-200 flex items-center justify-center text-gray-400 text-[11px] rounded">QR</div>
        )}
      </div>

      <hr className="border-gray-100 my-2" />

      {/* Trust signals */}
      {(card.seller_usage_description || card.condition_summary) && (
        <div className="flex flex-col gap-2 mb-2">
          {card.seller_usage_description && (
            <div className="bg-yellow-50/80 border border-yellow-200 rounded p-2 text-[12px] leading-relaxed">
              <div className="font-bold text-gray-900 text-[12px] mb-1">Seller says</div>
              <div>"{card.seller_usage_description}"</div>
              <div className="text-[11px] text-gray-500 mt-0.5">Self-declared by seller — not verified</div>
            </div>
          )}
          {card.condition_summary && (
            <div className="bg-blue-50/80 border border-blue-200 rounded p-2 text-[12px] leading-relaxed">
              <div className="font-bold text-gray-900 text-[12px] mb-1">Amazon AI independently assessed</div>
              <div>{card.condition_summary}</div>
              {card.usage_estimate && (
                <div className="mt-1 text-gray-700">Visible wear: {card.usage_estimate}</div>
              )}
              {card.care_recommendation && (
                <div className="mt-1 text-gray-500 italic">Care tip: {card.care_recommendation}</div>
              )}
            </div>
          )}
        </div>
      )}

      {/* Condition */}
      <div className="flex gap-2 mb-1">
        <span className="font-semibold min-w-[110px] text-gray-700">Condition</span>
        <span className={`font-bold ${condText}`}>{card.condition_grade}</span>
      </div>
      <div className="flex gap-2 mb-1">
        <span className="font-semibold min-w-[110px] text-gray-700">AI Confidence</span>
        <span>{Math.round(card.confidence * 100)}%</span>
      </div>
      <div className="flex gap-2 mb-1">
        <span className="font-semibold min-w-[110px] text-gray-700">Category</span>
        <span>{card.product_category}</span>
      </div>
      {card.brand_guess && (
        <div className="flex gap-2 mb-1">
          <span className="font-semibold min-w-[110px] text-gray-700">Brand</span>
          <span>{card.brand_guess}</span>
        </div>
      )}

      {/* Defects */}
      <div className="flex gap-2 mb-1">
        <span className="font-semibold min-w-[110px] text-gray-700">Defects</span>
        <span>
          {card.defects.length === 0
            ? "None detected"
            : card.defects.map((d) => `${d.defect_type} (${d.severity})`).join(", ")}
        </span>
      </div>

      <hr className="border-gray-100 my-2" />

      {/* Seller */}
      <div className="flex gap-2 mb-1">
        <span className="font-semibold min-w-[110px] text-gray-700">Seller</span>
        <span>{card.seller_name}</span>
      </div>
      <div className="flex gap-2 mb-1">
        <span className="font-semibold min-w-[110px] text-gray-700">City</span>
        <span>{card.seller_city}</span>
      </div>

      <hr className="border-gray-100 my-2" />

      {/* Trust footer */}
      <div className="bg-gray-100 p-2 rounded mb-2 text-[12px]">
        <div className="font-bold text-emerald-700">
          {card.amazon_guarantee ? "Amazon A-to-Z Guarantee Protected" : ""}
        </div>
        <div className="mt-1 italic text-gray-500">
          "This report was generated by Amazon's AI — not the seller. The seller cannot edit it."
        </div>
      </div>

      <div className="text-[11px] text-gray-400">
        Card URL:{" "}
        <a href={card.card_url} target="_blank" rel="noreferrer" className="text-amzn-blue">
          {card.card_url}
        </a>
      </div>
    </div>
  );
}
