"use client";
// components/HealthCardView.tsx
// Renders a HealthCard. QR base64 is NOT returned by the endpoint in the
// current schema — we display the card_url with a note for the QR.

import type { HealthCard } from "@/lib/types";

interface Props {
  card: HealthCard;
  qrBase64?: string; // optional — if endpoint returns it in future
}

const CONDITION_COLOR: Record<string, string> = {
  "Like New": "#007600",
  Good: "#0066c0",
  Fair: "#c45500",
  Poor: "#b12704",
};

export default function HealthCardView({ card, qrBase64 }: Props) {
  const condColor = CONDITION_COLOR[card.condition_grade] ?? "#555";

  return (
    <div style={styles.card}>
      {/* Header */}
      <div style={styles.header}>
        <div>
          <div style={styles.title}>Amazon Product Health Card</div>
          <div style={styles.cardId}>{card.card_uuid}</div>
        </div>
        {qrBase64 ? (
          <img
            src={`data:image/png;base64,${qrBase64}`}
            alt="QR code"
            style={{ width: 70, height: 70 }}
          />
        ) : (
          <div style={styles.qrPlaceholder}>QR</div>
        )}
      </div>

      <div style={styles.divider} />

      {/* Dual trust signals: seller declaration + AI independent assessment */}
      {(card.seller_usage_description || card.condition_summary) && (
        <div style={styles.trustSignals}>
          {card.seller_usage_description && (
            <div style={styles.sellerSignal}>
              <div style={styles.signalLabel}>🗣 Seller says</div>
              <div>"{card.seller_usage_description}"</div>
              <div style={{ fontSize: 11, color: "#888", marginTop: 2 }}>
                Self-declared by seller — not verified
              </div>
            </div>
          )}
          {card.condition_summary && (
            <div style={styles.aiSignal}>
              <div style={styles.signalLabel}>🤖 Amazon AI independently assessed</div>
              <div>{card.condition_summary}</div>
              {card.usage_estimate && (
                <div style={{ marginTop: 4, color: "#333" }}>
                  Visible wear: {card.usage_estimate}
                </div>
              )}
              {card.care_recommendation && (
                <div style={{ marginTop: 4, color: "#555", fontStyle: "italic" }}>
                  Care tip: {card.care_recommendation}
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* Condition */}
      <div style={styles.row}>
        <span style={styles.rowLabel}>Condition</span>
        <span style={{ color: condColor, fontWeight: 700 }}>{card.condition_grade}</span>
      </div>
      <div style={styles.row}>
        <span style={styles.rowLabel}>AI Confidence</span>
        <span>{Math.round(card.confidence * 100)}%</span>
      </div>
      <div style={styles.row}>
        <span style={styles.rowLabel}>Category</span>
        <span>{card.product_category}</span>
      </div>
      {card.brand_guess && (
        <div style={styles.row}>
          <span style={styles.rowLabel}>Brand</span>
          <span>{card.brand_guess}</span>
        </div>
      )}

      {/* Defects */}
      <div style={styles.row}>
        <span style={styles.rowLabel}>Defects</span>
        <span>
          {card.defects.length === 0
            ? "None detected"
            : card.defects.map((d) => `${d.defect_type} (${d.severity})`).join(", ")}
        </span>
      </div>

      <div style={styles.divider} />

      {/* Seller */}
      <div style={styles.row}>
        <span style={styles.rowLabel}>Seller</span>
        <span>{card.seller_name}</span>
      </div>
      <div style={styles.row}>
        <span style={styles.rowLabel}>City</span>
        <span>{card.seller_city}</span>
      </div>

      <div style={styles.divider} />

      {/* Trust footer */}
      <div style={styles.trust}>
        <div style={{ fontWeight: 700, color: "#007600" }}>
          {card.amazon_guarantee ? "✓ Amazon A-to-Z Guarantee Protected" : ""}
        </div>
        <div style={{ marginTop: 4, fontStyle: "italic", color: "#555" }}>
          "This report was generated by Amazon's AI — not the seller. The seller cannot edit
          it."
        </div>
      </div>

      <div style={styles.footer}>
        Card URL:{" "}
        <a href={card.card_url} target="_blank" rel="noreferrer" style={{ color: "#0066c0" }}>
          {card.card_url}
        </a>
      </div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  card: {
    border: "2px solid #ff9900",
    borderRadius: 4,
    padding: 16,
    background: "#fff",
    fontSize: 13,
    maxWidth: 500,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  title: { fontSize: 15, fontWeight: 700, color: "#111" },
  cardId: { fontSize: 11, color: "#888", marginTop: 2 },
  qrPlaceholder: {
    width: 70,
    height: 70,
    border: "1px solid #ccc",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#aaa",
    fontSize: 11,
    borderRadius: 3,
  },
  divider: { borderTop: "1px solid #eee", margin: "8px 0" },
  trustSignals: { marginBottom: 8, display: "flex", flexDirection: "column" as const, gap: 8 },
  sellerSignal: {
    background: "#fffbf0",
    border: "1px solid #ffe082",
    borderRadius: 3,
    padding: "8px 10px",
    fontSize: 12.5,
    lineHeight: 1.4,
  },
  aiSignal: {
    background: "#f0f7ff",
    border: "1px solid #d6e8ff",
    borderRadius: 3,
    padding: "8px 10px",
    fontSize: 12.5,
    lineHeight: 1.4,
  },
  signalLabel: { fontWeight: 700, marginBottom: 3, color: "#111", fontSize: 12 },
  summary: {
    background: "#f0f7ff",
    border: "1px solid #d6e8ff",
    borderRadius: 3,
    padding: "8px 10px",
    marginBottom: 8,
    fontSize: 12.5,
    lineHeight: 1.4,
  },
  row: { display: "flex", gap: 8, marginBottom: 4 },
  rowLabel: { fontWeight: 600, minWidth: 110, color: "#333" },
  trust: {
    background: "#f5f5f5",
    padding: "8px 10px",
    borderRadius: 3,
    marginBottom: 8,
    fontSize: 12,
  },
  footer: { fontSize: 11, color: "#888" },
};
